### PR TITLE
Edition notes for 1.1

### PR DESCRIPTION
**Pull request by bbdaniels**

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Looks all good to me. But should we add v1.1 somewhere? Lets call it version and then the publisher can deal with editions. As in there were no edition for the first versions. Or does this get complicated?

**Comment by bbdaniels** [comment]
I'd rather just use the terms non-specifically as done so as not to have to track more things. Publisher will probably have totally other ideas whatever we do, right?

**Comment by kbjarkefur** [comment]
How about a hard coded date? Or the sha uuid of the last included commit? 🤓 

I would think it would be neat to be able to pick any copy of the book in the future and go to the repo and find the exact commit it was compiled from.

**Comment by bbdaniels** [comment]
hahah that's a great idea -- is there any way to insert a SHA reference right in the code so it pulls automatically? I'll let that be a fun code project for you 😜

**Comment by kbjarkefur** [comment]
I am so close to solving it. I can do it by hardcoding which branch you are in, but that is not good enough.

Merge this and I will keep trying

**Pull request merged**
