### PR TITLE
Book skeleton

### PR DESCRIPTION
**Pull request by luizaandrade**

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Why was this branch merged? We decided to not merge this as this will create gnarly merge conflicts with branches that were created not from this.

**Comment by kbjarkefur** [comment]
We decided to keep it only for reference as the work you had done here was still helpful when re-writing chapters

**Comment by luizaandrade** [comment]
That's a very good question. I though I had only merged chapter 7. But it was late and I must have done something wrong.

**Comment by kbjarkefur** [comment]
Actually, this was merged by @bbdaniels into `bbd-ch7` in df1baa1ffba5565408ba8112c6f0f0239ea1d38c.

There were already a PR for the `book-skeleton` branch. And by merging `bbd-ch7` that included everything of `book-skeleton` to `develop` in #443 , this PR detected that in-directly it was merged to `develop`. And since you @luizaandrade merged #443, it also logged you as merging this PR.

**Comment by bbdaniels** [comment]
Oh that's interesting, but a nice behavior IMO. It must see that the current `develop` has the last commit here in its history.

**Pull request merged**
